export interface KeyData {
  name: string
  octave: number
  midi: number
  freq: number
  isBlack: boolean
  labelVi: string
  clef: 'bass' | 'treble'
}

export interface WhiteKeyData extends KeyData {
  blackKey?: KeyData
}

export const PIANO_STRUCTURE: WhiteKeyData[] = [
  {
    name: 'C3',
    octave: 3,
    midi: 48,
    freq: 130.81,
    isBlack: false,
    labelVi: 'Đô 3',
    clef: 'bass',
    blackKey: {
      name: 'C#3',
      octave: 3,
      midi: 49,
      freq: 138.59,
      isBlack: true,
      labelVi: 'Đô# 3',
      clef: 'bass',
    },
  },
  {
    name: 'D3',
    octave: 3,
    midi: 50,
    freq: 146.83,
    isBlack: false,
    labelVi: 'Rê 3',
    clef: 'bass',
    blackKey: {
      name: 'D#3',
      octave: 3,
      midi: 51,
      freq: 155.56,
      isBlack: true,
      labelVi: 'Rê# 3',
      clef: 'bass',
    },
  },
  {
    name: 'E3',
    octave: 3,
    midi: 52,
    freq: 164.81,
    isBlack: false,
    labelVi: 'Mi 3',
    clef: 'bass',
  },
  {
    name: 'F3',
    octave: 3,
    midi: 53,
    freq: 174.61,
    isBlack: false,
    labelVi: 'Fa 3',
    clef: 'bass',
    blackKey: {
      name: 'F#3',
      octave: 3,
      midi: 54,
      freq: 185.0,
      isBlack: true,
      labelVi: 'Fa# 3',
      clef: 'bass',
    },
  },
  {
    name: 'G3',
    octave: 3,
    midi: 55,
    freq: 196.0,
    isBlack: false,
    labelVi: 'Sol 3',
    clef: 'bass',
    blackKey: {
      name: 'G#3',
      octave: 3,
      midi: 56,
      freq: 207.65,
      isBlack: true,
      labelVi: 'Sol# 3',
      clef: 'bass',
    },
  },
  {
    name: 'A3',
    octave: 3,
    midi: 57,
    freq: 220.0,
    isBlack: false,
    labelVi: 'La 3',
    clef: 'bass',
    blackKey: {
      name: 'A#3',
      octave: 3,
      midi: 58,
      freq: 233.08,
      isBlack: true,
      labelVi: 'La# 3',
      clef: 'bass',
    },
  },
  {
    name: 'B3',
    octave: 3,
    midi: 59,
    freq: 246.94,
    isBlack: false,
    labelVi: 'Si 3',
    clef: 'bass',
  },
  {
    name: 'C4',
    octave: 4,
    midi: 60,
    freq: 261.63,
    isBlack: false,
    labelVi: 'Đô Giữa (C4)',
    clef: 'treble',
    blackKey: {
      name: 'C#4',
      octave: 4,
      midi: 61,
      freq: 277.18,
      isBlack: true,
      labelVi: 'Đô# 4',
      clef: 'treble',
    },
  },
  {
    name: 'D4',
    octave: 4,
    midi: 62,
    freq: 293.66,
    isBlack: false,
    labelVi: 'Rê 4',
    clef: 'treble',
    blackKey: {
      name: 'D#4',
      octave: 4,
      midi: 63,
      freq: 311.13,
      isBlack: true,
      labelVi: 'Rê# 4',
      clef: 'treble',
    },
  },
  {
    name: 'E4',
    octave: 4,
    midi: 64,
    freq: 329.63,
    isBlack: false,
    labelVi: 'Mi 4',
    clef: 'treble',
  },
  {
    name: 'F4',
    octave: 4,
    midi: 65,
    freq: 349.23,
    isBlack: false,
    labelVi: 'Fa 4',
    clef: 'treble',
    blackKey: {
      name: 'F#4',
      octave: 4,
      midi: 66,
      freq: 369.99,
      isBlack: true,
      labelVi: 'Fa# 4',
      clef: 'treble',
    },
  },
  {
    name: 'G4',
    octave: 4,
    midi: 67,
    freq: 392.0,
    isBlack: false,
    labelVi: 'Sol 4',
    clef: 'treble',
    blackKey: {
      name: 'G#4',
      octave: 4,
      midi: 68,
      freq: 415.3,
      isBlack: true,
      labelVi: 'Sol# 4',
      clef: 'treble',
    },
  },
  {
    name: 'A4',
    octave: 4,
    midi: 69,
    freq: 440.0,
    isBlack: false,
    labelVi: 'La 4 (A440)',
    clef: 'treble',
    blackKey: {
      name: 'A#4',
      octave: 4,
      midi: 70,
      freq: 466.16,
      isBlack: true,
      labelVi: 'La# 4',
      clef: 'treble',
    },
  },
  {
    name: 'B4',
    octave: 4,
    midi: 71,
    freq: 493.88,
    isBlack: false,
    labelVi: 'Si 4',
    clef: 'treble',
  },
  {
    name: 'C5',
    octave: 5,
    midi: 72,
    freq: 523.25,
    isBlack: false,
    labelVi: 'Đô 5',
    clef: 'treble',
  },
]
